GET http://localhost:3000/test/user
Accept: application/json

###
GET http://localhost:3000/test/user/typescript
Accept: application/json

###
POST http://localhost:3000/test/user
Content-Type: application/json

{
  "id": 123
}

### delete test RbacGuard
DELETE http://localhost:3000/test/user/123
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphdmFzY3JpcHQiLCJzdWIiOjEsInJlYWxOYW1lIjoic2NyaXB0Iiwicm9sZSI6MywiaWF0IjoxNjI4NDA4NzkwLCJleHAiOjE2Mjg0Mzc1OTB9.Uxy9otoKoh3rclrMPyBiiu9AXnCJMR1ks2Yt_GS2c-4
### delete test RbacInterceptor
DELETE http://localhost:3000/test/user/remove
Content-Type: application/json

###
PATCH http://localhost:3000/test/user/123
Content-Type: application/json

### 带token
PATCH http://localhost:3000/test/user/123
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphdmFzY3JpcHQiLCJzdWIiOjEsInJlYWxOYW1lIjoic2NyaXB0Iiwicm9sZSI6MywiaWF0IjoxNjI4MzI3ODI0LCJleHAiOjE2MjgzNTY2MjR9.C6GsqkVgyyKDzgidISLP2mUHbhGhJrl7TH7VwN1jYVI

###
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "nickname": "123123",
  "password": "password",
  "repassword": "password",
  "mobile": "18718033902"
}
### DTO管道测试
POST http://localhost:3000/test/user/register
Content-Type: application/json

{
  "accountName": "account test 1",
  "realName": "real name test 1",
  "password": "password",
  "repassword": "password",
  "mobile": "10086"
}

###
POST http://localhost:3000/test/user/login
Content-Type: application/json

{
  "username": "javascript",
  "password": "123456"
}

###